#!/usr/bin/ruby

require 'rubygems'

version = ">= 0"

if ARGV.first =~ /^_(.*)_$/ and Gem::Version.correct? $1 then
  version = $1
  ARGV.shift
end

require 'jekyll'

# Dynamically add other tags on a per site basis
if File.directory?('_liquid_extensions')
  Dir.chdir('_liquid_extensions') do
    Dir['*.rb'].each do |file|
      require file
    end
  end
end

gem 'jekyll', version
load Gem.bin_path('jekyll', 'jekyll', version)
